import type { Era } from '../core/types';
import { create1962 } from './y1962';
import { create1972 } from './y1972';
import { create1978 } from './y1978';
import { create1980 } from './y1980';
import { create1984 } from './y1984';
import { create1985 } from './y1985';
import { create1992 } from './y1992';
import { create1993 } from './y1993';
import { create1996 } from './y1996';
import { create2009 } from './y2009';
import { create2013 } from './y2013';
import { create2017 } from './y2017';
import { Game2000 } from './y2000';
import { Game2004 } from './y2004';
import { Game2026 } from './y2026';

export const ERAS: Era[] = [
  {
    id: 'y1962',
    year: 1962,
    label: '1962',
    title: 'TWO DOTS AND A STAR',
    tagline: ['WELCOME TO 1962.', 'THE COMPUTER IS THE SIZE OF A WARDROBE.', 'IT IS ABOUT TO BE MISUSED.'],
    controls: 'TURN: ← →   THRUST: ↑   FIRE: SPACE',
    theme: 'oscilloscope',
    duration: 40,
    fact: 'Spacewar! was written in 1962 by students at MIT on a PDP-1, a machine that cost roughly $120,000. It was never sold. It was copied, by hand, onto every PDP-1 anyone could reach.',
    deepDive: {
      developer: 'Steve Russell and the MIT Tech Model Railroad Club',
      release: '1962',
      platform: 'DEC PDP-1 with a point-plotting CRT display',
      innovation: 'Real-time two-player action with simulated gravity and inertia, years before anyone sold a game.',
      why: 'It proved a computer could be played with rather than only computed on, and it spread to university labs as free, shared code.',
      funFact: 'The display was a circular scope descended from radar hardware. Programmers added a star field for orientation because empty black was disorienting.',
    },
    touch: { dpad: true, action: 'FIRE' },
    play: { kind: 'canvas', create: create1962 },
  },
  {
    id: 'y1972',
    year: 1972,
    label: '1972',
    title: 'TWO RECTANGLES',
    tagline: ['WELCOME TO 1972.', 'WE HAVE TWO RECTANGLES.', 'AND A SQUARE.', 'ENJOY.'],
    controls: 'MOVE: ↑ ↓  or mouse',
    theme: 'arcade',
    duration: 32,
    fact: 'Pong was one of the first commercially successful arcade games. Its takings turned video games from a laboratory curiosity into an industry with cabinets, routes and competitors.',
    deepDive: {
      developer: 'Atari (Allan Alcorn, as a training exercise)',
      release: '1972',
      platform: 'Purpose-built arcade hardware — no CPU, no code, just logic chips',
      innovation: 'A paddle that changes the ball angle depending on where it hits. One rule, endless rallies.',
      why: 'It was the first video game most people ever saw, and the first to make real money, which decided how the next decade was funded.',
      funFact: 'The Magnavox Odyssey had shipped a tennis game months earlier. The resulting legal argument ran for years.',
    },
    touch: { dpad: true, action: false, pointer: true },
    play: { kind: 'canvas', create: create1972 },
  },
  {
    id: 'y1978',
    year: 1978,
    label: '1978',
    title: 'DESCENDING GRID',
    tagline: ['1978.', 'THE ALIENS ARRIVE IN NEAT ROWS.', 'THEY WILL NOT STAY THAT WAY.'],
    controls: 'MOVE: ← →   FIRE: SPACE',
    theme: 'arcade',
    duration: 34,
    fact: 'Space Invaders sped up as you cleared it — not by design, but because the hardware could redraw fewer aliens faster. The accident became the template for arcade difficulty.',
    deepDive: {
      developer: 'Taito, designed by Tomohiro Nishikado',
      release: '1978',
      platform: 'Arcade, on hardware Nishikado partly built himself',
      innovation: 'Enemies that shoot back and a score that persists on screen, which invented the high-score culture.',
      why: 'It made the arcade a destination rather than a sideline, and it made the high-score table a social object.',
      funFact: 'The marching bass line speeds up with the aliens. It may be the first piece of adaptive music in a game, and it was a side effect.',
    },
    touch: { horizontal: true, action: 'FIRE' },
    play: { kind: 'canvas', create: create1978 },
  },
  {
    id: 'y1980',
    year: 1980,
    label: '1980',
    title: 'DOT MANAGEMENT',
    tagline: ['1980.', 'EAT THE DOTS.', 'THE DOTS ARE NOT THE PROBLEM.'],
    controls: 'MOVE: ARROW KEYS',
    theme: 'arcade',
    duration: 40,
    fact: 'Pac-Man gave each ghost its own chase rule rather than one shared behaviour, so the maze felt like it was being hunted by four personalities instead of four copies.',
    deepDive: {
      developer: 'Namco, designed by Toru Iwatani',
      release: '1980',
      platform: 'Arcade',
      innovation: 'Four enemies with distinct pursuit logic, and a power-up that inverts the entire relationship for a few seconds.',
      why: 'It deliberately aimed past the young men who filled arcades, and the audience it found changed who games were made for.',
      funFact: 'One ghost chases you directly, one aims ahead of you, and one is semi-random. Players invented patterns to beat them, and the patterns worked.',
    },
    touch: { dpad: true, action: false },
    play: { kind: 'canvas', create: create1980 },
  },
  {
    id: 'y1984',
    year: 1984,
    label: '1984',
    title: 'FALLING SHAPES',
    tagline: ['1984.', 'SHAPES FALL.', 'YOU ARRANGE THEM.', 'THAT IS THE WHOLE GAME.'],
    controls: 'MOVE: ← →   ROTATE: ↑   DROP: SPACE',
    theme: 'bit8',
    duration: 27,
    fact: 'Tetris was written in 1984 by Alexey Pajitnov on a Soviet Electronika 60, a machine with no graphics — the first version drew its blocks out of text characters.',
    deepDive: {
      developer: 'Alexey Pajitnov at the Soviet Academy of Sciences',
      release: '1984',
      platform: 'Electronika 60, then every machine ever built',
      innovation: 'An endless game with no win state, where the reward is simply not losing for longer.',
      why: 'Bundled with the Game Boy in 1989, it proved that a game could sell hardware to people who did not consider themselves players.',
      funFact: 'Who actually owned the rights took years and several countries to resolve. Pajitnov saw no money from it until 1996.',
    },
    touch: { dpad: true, action: 'DROP' },
    play: { kind: 'canvas', create: create1984 },
  },
  {
    id: 'y1985',
    year: 1985,
    label: '1985',
    title: 'RUN AND JUMP',
    tagline: ['1985.', 'GO RIGHT.', 'JUMP OVER THINGS.', 'HOW HARD CAN IT BE.'],
    controls: 'MOVE: ← →   JUMP: SPACE',
    theme: 'bit8',
    duration: 45,
    fact: 'Super Mario Bros. teaches you to run, jump and fear a gap in its first few seconds, without a single line of instruction. The opening screen is a tutorial pretending to be scenery.',
    deepDive: {
      developer: 'Nintendo, designed by Shigeru Miyamoto and Takashi Tezuka',
      release: '1985',
      platform: 'Nintendo Entertainment System',
      innovation: 'Momentum-based jumping with variable height, so skill lives in how long you hold the button.',
      why: 'It arrived after the 1983 crash had emptied shelves in North America, and it was the reason the shelves filled again.',
      funFact: 'The famous cloud and bush sprites are the same shape in different colours. Cartridge space was measured in kilobytes.',
    },
    touch: { horizontal: true, action: 'JUMP' },
    play: { kind: 'canvas', create: create1985 },
  },
  {
    id: 'y1992',
    year: 1992,
    label: '1992',
    title: 'TWO FIGHTERS',
    tagline: ['1992.', 'ROUND ONE.', 'BALANCING HAS NOT BEEN INVENTED YET.'],
    controls: 'MOVE: ← →   PUNCH: SPACE',
    theme: 'bit16',
    duration: 45,
    fact: 'Street Fighter II turned the arcade into a competitive venue. Its combo system was a bug: an animation window that let a second hit land before the opponent could recover.',
    deepDive: {
      developer: 'Capcom',
      release: '1991 in arcades, 1992 on home hardware',
      innovation: 'Eight distinct characters with different reach, speed and recovery, which made the match a conversation rather than a race.',
      platform: 'Arcade, then Super Nintendo',
      why: 'It created the idea of playing against the person next to you for status, and with it the whole fighting-game scene.',
      funFact: 'The developers found the combo bug before release and left it in, assuming nobody would ever execute it reliably.',
    },
    touch: { horizontal: true, action: 'PUNCH' },
    play: { kind: 'canvas', create: create1992 },
  },
  {
    id: 'y1993',
    year: 1993,
    label: '1993',
    title: 'THE THIRD DIMENSION',
    tagline: ['1993.', 'WE ADDED A DIMENSION.', 'NOT A REAL ONE.', 'PLEASE ACT IMPRESSED.'],
    controls: 'MOVE: ↑ ↓   TURN: ← →   SHOOT: SPACE',
    theme: 'bit16',
    duration: 35,
    fact: 'Doom looked three-dimensional but could not stack one room above another. Its world was flat geometry with heights — enough of an illusion that nobody minded for years.',
    deepDive: {
      developer: 'id Software',
      release: '1993',
      platform: 'MS-DOS, then everything with a processor in it',
      innovation: 'Fast first-person rendering on ordinary office PCs, plus deathmatch over a local network.',
      why: 'Shareware distribution let it spread by copying rather than retail, and it made the PC the home of a genre.',
      funFact: 'Its levels, enemies and weapons were data files rather than code, so players started modifying it almost immediately. Modding as a hobby starts about here.',
    },
    touch: { dpad: true, action: 'SHOOT' },
    play: { kind: 'canvas', create: create1993 },
  },
  {
    id: 'y1996',
    year: 1996,
    label: '1996',
    title: 'ACTUAL POLYGONS',
    tagline: ['1996.', 'EVERYTHING IS MADE OF TRIANGLES NOW.', 'TRY NOT TO LOOK AT THE FOG.'],
    controls: 'MOVE: ↑   TURN: ← →',
    theme: 'early3d',
    duration: 30,
    fact: 'Early 3D consoles hid their draw distance behind fog, because the alternative was watching the world appear out of nothing a few metres in front of you.',
    deepDive: {
      developer: 'Nintendo, Sony, Sega and everyone else, simultaneously',
      release: '1996 — Super Mario 64, Quake, Tomb Raider, all within months',
      platform: 'Nintendo 64, PlayStation, PC',
      innovation: 'A camera you control and an analogue stick to move in any direction, which required inventing the modern control scheme from scratch.',
      why: 'Every convention of 3D movement — the stick, the camera behind the shoulder, the fog — was argued out in about eighteen months.',
      funFact: 'PlayStation geometry wobbles because the hardware snapped vertices to whole pixels. The jitter was never intended, and is now a deliberate art style.',
    },
    touch: { dpad: true, action: false },
    play: { kind: 'canvas', create: create1996 },
  },
  {
    id: 'y2000',
    year: 2000,
    label: '2000',
    title: 'CONNECTING',
    tagline: ['2000.', 'OTHER PEOPLE ARE OUT THERE.', 'THEY ARE ABOUT 420 MILLISECONDS AWAY.'],
    controls: 'CLICK THE TARGETS',
    theme: 'web2',
    duration: 35,
    fact: 'Playing online meant occupying the household telephone line. A 56k modem negotiated its speed out loud, and anyone picking up the handset ended the match.',
    deepDive: {
      developer: 'Everyone, over dial-up',
      release: 'c. 1996–2002',
      platform: 'PC, modem, one telephone line, one family',
      innovation: 'Client-side prediction: the game guesses what the server will say so your own movement feels instant.',
      why: 'Persistent servers and ladders turned games into places you returned to rather than things you finished.',
      funFact: 'Players learned to aim where an opponent would be rather than where they appeared. High-ping players developed a genuinely different playstyle.',
    },
    touch: { action: false, pointer: true },
    play: { kind: 'react', Component: Game2000 },
  },
  {
    id: 'y2004',
    year: 2004,
    label: '2004',
    title: 'SAVE THE KINGDOM',
    tagline: ['2004.', 'THE WORLD IS ENORMOUS.', 'SO IS THE TO-DO LIST.'],
    controls: 'CLICK TO HARVEST',
    theme: 'web2',
    duration: 40,
    fact: 'World of Warcraft reached roughly 12 million subscribers. The quest structure that drew people in — collect, return, repeat — was also the thing most of them eventually described as a job.',
    deepDive: {
      developer: 'Blizzard Entertainment',
      release: '2004',
      platform: 'PC and Mac',
      innovation: 'A shared persistent world that an ordinary machine could run, with a quest log that explained where to go next.',
      why: 'It normalised the monthly subscription, the guild as a social group, and the idea that a game could be where you spend your evenings for years.',
      funFact: 'The early collection quests often had drop rates below 20 percent, meaning "collect 10" quietly meant "kill 50". The maths was deliberate.',
    },
    touch: { action: false, pointer: true },
    play: { kind: 'react', Component: Game2004 },
  },
  {
    id: 'y2009',
    year: 2009,
    label: '2009',
    title: 'POCKET SIZED',
    tagline: ['2009.', 'THE WHOLE INDUSTRY FITS IN A POCKET.', 'IT WOULD LIKE YOUR ATTENTION.'],
    controls: 'TAP THE BUBBLES',
    theme: 'flat',
    duration: 35,
    fact: 'The App Store opened in 2008 and made a game cost less than a coffee. Within two years the energy timer had been invented, so the cheap game could sell you the right to keep playing it.',
    deepDive: {
      developer: 'Thousands of very small studios',
      release: '2008 onwards',
      platform: 'Touchscreen phones',
      innovation: 'Direct manipulation — no buttons between your finger and the thing on screen.',
      why: 'It brought in an audience that had never owned a console, and it rewrote how games are priced.',
      funFact: 'Energy systems came from social network games, where the timer existed to make you return daily and invite friends while you waited.',
    },
    touch: { action: false, pointer: true },
    play: { kind: 'canvas', create: create2009 },
  },
  {
    id: 'y2013',
    year: 2013,
    label: '2013',
    title: 'SOME ASSEMBLY REQUIRED',
    tagline: ['2013.', 'THE GAME IS FREE.', 'THE VERBS ARE NOT.'],
    controls: 'MOVE: ← →   JUMP: SPACE',
    theme: 'flat',
    duration: 40,
    fact: 'Free-to-play became the dominant model in the early 2010s. The design question shifted from "is this fun" to "where does the player feel the friction most" — because that is where the shop goes.',
    deepDive: {
      developer: 'The entire mobile and PC market',
      release: 'c. 2009–2015',
      platform: 'Everywhere, eventually',
      innovation: 'Revenue separated from the price of entry, so a game could be free and still fund a studio.',
      why: 'It funded enormous free games and a decade of argument about loot boxes, several of which ended in national regulators.',
      funFact: 'A small fraction of players provide most of the revenue in these games. The industry had a nickname for them, and it was not a flattering one.',
    },
    touch: { horizontal: true, action: 'JUMP' },
    play: { kind: 'canvas', create: create2013 },
  },
  {
    id: 'y2017',
    year: 2017,
    label: '2017',
    title: 'NINETY-NINE OTHERS',
    tagline: ['2017.', 'ONE HUNDRED PLAYERS.', 'NINETY-NINE PROBLEMS, RESOLVING THEMSELVES.'],
    controls: 'MOVE: ARROW KEYS',
    theme: 'modern',
    duration: 25,
    fact: 'Battle royale came out of mod culture — community-made rulesets for existing games — before anyone built a standalone one. Within a year it was the shape of the biggest game in the world.',
    deepDive: {
      developer: 'Brendan Greene, then PUBG Corporation and Epic Games',
      release: '2017',
      platform: 'PC and console, then phones',
      innovation: 'A shrinking play area that forces an ending, which solved the problem of matches that never finish.',
      why: 'It made a game a place to meet friends, and turned the free seasonal update into the default business model for big games.',
      funFact: 'The shrinking circle exists purely as a pacing device. Without it, a hundred cautious players would simply hide until everyone logged off.',
    },
    touch: { dpad: true, action: false },
    play: { kind: 'canvas', create: create2017 },
  },
  {
    id: 'y2026',
    year: 2026,
    label: '2020s',
    title: 'PLEASE WAIT',
    tagline: ['THE 2020s.', '12,000 PEOPLE WORKED ON THIS GAME.', "YOU'RE PRESSING ONE BUTTON."],
    controls: 'PRESS SPACE. EVENTUALLY.',
    theme: 'modern',
    duration: 35,
    fact: 'A modern blockbuster credits thousands of people across several countries, ships a day-one patch larger than every game on this timeline combined, and still has to compile its shaders on your machine before you can move.',
    deepDive: {
      developer: 'Several studios, several continents, several years',
      release: 'The 2020s',
      platform: 'Consoles, PC, streaming, phones, whatever is next',
      innovation: 'Photoreal rendering, enormous worlds, and patching as a permanent condition rather than an emergency.',
      why: 'Budgets now rival film, which makes risk expensive and sequels safe. The interesting work increasingly happens in smaller teams.',
      funFact: 'Shader compilation happens on your hardware because there are too many possible GPU combinations to pre-build. That progress bar is your own computer doing the studio’s last build step.',
    },
    touch: { action: false, pointer: true },
    play: { kind: 'react', Component: Game2026 },
  },
];

export const eraById = (id: string) => ERAS.find((e) => e.id === id);
export const nextEra = (id: string) => {
  const i = ERAS.findIndex((e) => e.id === id);
  return i >= 0 && i < ERAS.length - 1 ? ERAS[i + 1] : null;
};
