import type { Era } from '../core/types';
import { create1962 } from './y1962';
import { create1972 } from './y1972';
import { create1978 } from './y1978';
import { create1980 } from './y1980';
import { create1984 } from './y1984';
import { create1985 } from './y1985';
import { create1992 } from './y1992';
import { create1993 } from './y1993';
import { create1996 } from './y1996';
import { create2009 } from './y2009';
import { create2013 } from './y2013';
import { create1981 } from './y1981';
import { create1991 } from './y1991';
import { create1994 } from './y1994';
import { create1997 } from './y1997';
import { create2001 } from './y2001';
import { create2011 } from './y2011';
import { create2016 } from './y2016';
import { create2017 } from './y2017';
import { Game2000 } from './y2000';
import { Game2004 } from './y2004';
import { Game2026 } from './y2026';

export const ERAS: Era[] = [
  {
    id: 'y1962',
    year: 1962,
    label: '1962',
    title: 'TWO DOTS AND A STAR',
    tagline: ['WELCOME TO 1962.', 'THE COMPUTER IS THE SIZE OF A WARDROBE.', 'IT IS ABOUT TO BE MISUSED.'],
    controls: 'TURN: ← →   THRUST: ↑   FIRE: SPACE',
    touchControls: 'Hold anywhere to steer and thrust. It fires by itself.',
    goal: 'Hit the rival ship before the night shift wants the computer back.',
    theme: 'oscilloscope',
    duration: 60,
    fact: 'Spacewar! was written in 1962 by students at MIT on a PDP-1, a machine that cost roughly $120,000. It was never sold. It was copied, by hand, onto every PDP-1 anyone could reach.',
    deepDive: {
      developer: 'Steve Russell and the MIT Tech Model Railroad Club',
      release: '1962',
      platform: 'DEC PDP-1 with a point-plotting CRT display',
      innovation: 'Real-time two-player action with simulated gravity and inertia, years before anyone sold a game.',
      why: 'It proved a computer could be played with rather than only computed on, and it spread to university labs as free, shared code.',
      funFact: 'The display was a circular scope descended from radar hardware. Programmers added a star field for orientation because empty black was disorienting.',
    },
    play: { kind: 'canvas', create: create1962 },
  },
  {
    id: 'y1972',
    year: 1972,
    label: '1972',
    title: 'TWO RECTANGLES',
    tagline: ['WELCOME TO 1972.', 'WE HAVE TWO RECTANGLES.', 'AND A SQUARE.', 'ENJOY.'],
    controls: 'MOVE: ↑ ↓  or mouse',
    touchControls: 'Slide your thumb. The paddle follows it.',
    goal: 'Survive the round. Mind your lives.',
    theme: 'arcade',
    duration: 46,
    fact: 'Pong was one of the first commercially successful arcade games. Its takings turned video games from a laboratory curiosity into an industry with cabinets, routes and competitors.',
    deepDive: {
      developer: 'Atari (Allan Alcorn, as a training exercise)',
      release: '1972',
      platform: 'Purpose-built arcade hardware — no CPU, no code, just logic chips',
      innovation: 'A paddle that changes the ball angle depending on where it hits. One rule, endless rallies.',
      why: 'It was the first video game most people ever saw, and the first to make real money, which decided how the next decade was funded.',
      funFact: 'The Magnavox Odyssey had shipped a tennis game months earlier. The resulting legal argument ran for years.',
    },
    play: { kind: 'canvas', create: create1972 },
  },
  {
    id: 'y1978',
    year: 1978,
    label: '1978',
    title: 'DESCENDING GRID',
    tagline: ['1978.', 'THE ALIENS ARRIVE IN NEAT ROWS.', 'THEY WILL NOT STAY THAT WAY.'],
    controls: 'MOVE: ← →   FIRE: SPACE',
    touchControls: 'Hold and slide. Holding also shoots.',
    goal: 'Clear the waves, then whatever arrives after them.',
    theme: 'arcade',
    duration: 48,
    fact: 'Space Invaders sped up as you cleared it — not by design, but because the hardware could redraw fewer aliens faster. The accident became the template for arcade difficulty.',
    deepDive: {
      developer: 'Taito, designed by Tomohiro Nishikado',
      release: '1978',
      platform: 'Arcade, on hardware Nishikado partly built himself',
      innovation: 'Enemies that shoot back and a score that persists on screen, which invented the high-score culture.',
      why: 'It made the arcade a destination rather than a sideline, and it made the high-score table a social object.',
      funFact: 'The marching bass line speeds up with the aliens. It may be the first piece of adaptive music in a game, and it was a side effect.',
    },
    play: { kind: 'canvas', create: create1978 },
  },
  {
    id: 'y1980',
    year: 1980,
    label: '1980',
    title: 'DOT MANAGEMENT',
    tagline: ['1980.', 'EAT THE DOTS.', 'THE DOTS ARE NOT THE PROBLEM.'],
    controls: 'MOVE: ARROW KEYS',
    touchControls: 'Swipe or hold and steer.',
    goal: 'Eat your fill. Then catch all three ghosts.',
    theme: 'arcade',
    duration: 55,
    fact: 'Pac-Man gave each ghost its own chase rule rather than one shared behaviour, so the maze felt like it was being hunted by four personalities instead of four copies.',
    deepDive: {
      developer: 'Namco, designed by Toru Iwatani',
      release: '1980',
      platform: 'Arcade',
      innovation: 'Four enemies with distinct pursuit logic, and a power-up that inverts the entire relationship for a few seconds.',
      why: 'It deliberately aimed past the young men who filled arcades, and the audience it found changed who games were made for.',
      funFact: 'One ghost chases you directly, one aims ahead of you, and one is semi-random. Players invented patterns to beat them, and the patterns worked.',
    },
    play: { kind: 'canvas', create: create1980 },
  },
  {
    id: 'y1981',
    year: 1981,
    label: '1981',
    title: 'BARREL CLIMB',
    tagline: ['1981.', 'HE IS AT THE TOP.', 'HE HAS BARRELS.', 'THAT IS THE PLOT.'],
    controls: 'MOVE: \u2190 \u2192   CLIMB: \u2191 \u2193   JUMP: SPACE',
    touchControls: 'Hold and slide to walk, up or down to climb, tap to jump.',
    goal: 'Climb five girders without meeting a barrel.',
    theme: 'arcade',
    duration: 45,
    fact: 'Donkey Kong gave arcade games a story: a villain, a victim and a climb. It also gave a struggling company its future, and a carpenter his career.',
    deepDive: {
      developer: 'Nintendo, designed by Shigeru Miyamoto',
      release: '1981',
      platform: 'Arcade',
      innovation: 'Cut-scenes between levels and a goal you climb towards, rather than a score you accumulate.',
      why: 'It was Nintendo\u2019s first hit outside Japan, built by converting unsold cabinets of a failed game, and it started the platform genre.',
      funFact: 'The hero was called Jumpman, because jumping was the new mechanic and nobody had thought of a name yet.',
    },
    play: { kind: 'canvas', create: create1981 },
  },
  {
    id: 'y1984',
    year: 1984,
    label: '1984',
    title: 'FALLING SHAPES',
    tagline: ['1984.', 'SHAPES FALL.', 'YOU ARRANGE THEM.', 'THAT IS THE WHOLE GAME.'],
    controls: 'MOVE: ← →   ROTATE: ↑   DROP: SPACE',
    touchControls: 'Swipe sideways to move, down to drop, tap to rotate.',
    goal: 'Clear your lines before the speed clears you.',
    theme: 'bit8',
    duration: 45,
    fact: 'Tetris was written in 1984 by Alexey Pajitnov on a Soviet Electronika 60, a machine with no graphics — the first version drew its blocks out of text characters.',
    deepDive: {
      developer: 'Alexey Pajitnov at the Soviet Academy of Sciences',
      release: '1984',
      platform: 'Electronika 60, then every machine ever built',
      innovation: 'An endless game with no win state, where the reward is simply not losing for longer.',
      why: 'Bundled with the Game Boy in 1989, it proved that a game could sell hardware to people who did not consider themselves players.',
      funFact: 'Who actually owned the rights took years and several countries to resolve. Pajitnov saw no money from it until 1996.',
    },
    play: { kind: 'canvas', create: create1984 },
  },
  {
    id: 'y1985',
    year: 1985,
    label: '1985',
    title: 'RUN AND JUMP',
    tagline: ['1985.', 'GO RIGHT.', 'JUMP OVER THINGS.', 'HOW HARD CAN IT BE.'],
    controls: 'MOVE: ← →   JUMP: SPACE',
    touchControls: 'Hold and slide to run. Tap or flick up to jump.',
    goal: 'Reach the flag. It is further than it looks.',
    theme: 'bit8',
    duration: 60,
    fact: 'Super Mario Bros. teaches you to run, jump and fear a gap in its first few seconds, without a single line of instruction. The opening screen is a tutorial pretending to be scenery.',
    deepDive: {
      developer: 'Nintendo, designed by Shigeru Miyamoto and Takashi Tezuka',
      release: '1985',
      platform: 'Nintendo Entertainment System',
      innovation: 'Momentum-based jumping with variable height, so skill lives in how long you hold the button.',
      why: 'It arrived after the 1983 crash had emptied shelves in North America, and it was the reason the shelves filled again.',
      funFact: 'The famous cloud and bush sprites are the same shape in different colours. Cartridge space was measured in kilobytes.',
    },
    play: { kind: 'canvas', create: create1985 },
  },
  {
    id: 'y1991',
    year: 1991,
    label: '1991',
    title: 'LOOP RUNNER',
    tagline: ['1991.', 'THE CONSOLE WAR NEEDED A MASCOT.', 'THIS ONE GOES FAST.'],
    controls: 'JUMP: SPACE   (it runs by itself)',
    touchControls: 'Tap to jump. Hold in the air to roll.',
    goal: 'Reach the end. Keep at least one ring.',
    theme: 'bit16',
    duration: 45,
    fact: 'Sonic existed to be the thing the other mascot was not: fast, impatient, and bundled with the console. Speed was a marketing position before it was a mechanic.',
    deepDive: {
      developer: 'Sega, Sonic Team',
      release: '1991',
      platform: 'Mega Drive / Genesis',
      innovation: 'Momentum physics on curved ground, so loops and ramps worked without scripting.',
      why: 'Bundling it with the console turned a distant second place into a genuine console war, which is why the early nineties had one.',
      funFact: 'The rings exist so beginners rarely die outright. Losing a hundred rings feels worse than losing a life, and costs less.',
    },
    play: { kind: 'canvas', create: create1991 },
  },
  {
    id: 'y1992',
    year: 1992,
    label: '1992',
    title: 'TWO FIGHTERS',
    tagline: ['1992.', 'ROUND ONE.', 'BALANCING HAS NOT BEEN INVENTED YET.'],
    controls: 'MOVE: ← →   PUNCH: SPACE',
    touchControls: 'Hold and slide to move. Tap to punch.',
    goal: 'Win three rounds. Round one does not count for much.',
    theme: 'bit16',
    duration: 60,
    fact: 'Street Fighter II turned the arcade into a competitive venue. Its combo system was a bug: an animation window that let a second hit land before the opponent could recover.',
    deepDive: {
      developer: 'Capcom',
      release: '1991 in arcades, 1992 on home hardware',
      innovation: 'Eight distinct characters with different reach, speed and recovery, which made the match a conversation rather than a race.',
      platform: 'Arcade, then Super Nintendo',
      why: 'It created the idea of playing against the person next to you for status, and with it the whole fighting-game scene.',
      funFact: 'The developers found the combo bug before release and left it in, assuming nobody would ever execute it reliably.',
    },
    play: { kind: 'canvas', create: create1992 },
  },
  {
    id: 'y1993',
    year: 1993,
    label: '1993',
    title: 'THE THIRD DIMENSION',
    tagline: ['1993.', 'WE ADDED A DIMENSION.', 'NOT A REAL ONE.', 'PLEASE ACT IMPRESSED.'],
    controls: 'MOVE: ↑ ↓   TURN: ← →   SHOOT: SPACE',
    touchControls: 'Drag to look and walk. Tap to shoot.',
    goal: 'Clear the corridor before it clears you.',
    theme: 'bit16',
    duration: 50,
    fact: 'Doom looked three-dimensional but could not stack one room above another. Its world was flat geometry with heights — enough of an illusion that nobody minded for years.',
    deepDive: {
      developer: 'id Software',
      release: '1993',
      platform: 'MS-DOS, then everything with a processor in it',
      innovation: 'Fast first-person rendering on ordinary office PCs, plus deathmatch over a local network.',
      why: 'Shareware distribution let it spread by copying rather than retail, and it made the PC the home of a genre.',
      funFact: 'Its levels, enemies and weapons were data files rather than code, so players started modifying it almost immediately. Modding as a hobby starts about here.',
    },
    play: { kind: 'canvas', create: create1993 },
  },
  {
    id: 'y1994',
    year: 1994,
    label: '1994',
    title: 'FOUR WORDS IN A BOX',
    tagline: ['1994.', 'A MENU APPEARS.', 'THIS IS COMBAT NOW.'],
    controls: 'MOVE: ARROWS   CHOOSE: SPACE',
    touchControls: 'Tap a command when the bar is ready.',
    goal: 'Survive the random encounters.',
    theme: 'bit16',
    duration: 55,
    fact: 'Japanese role-playing games turned fighting into a conversation with a menu. The Active Time Battle bar added pressure to that conversation, and an entire decade of games copied it.',
    deepDive: {
      developer: 'Square, Enix and the studios that followed them',
      release: 'Final Fantasy VI, 1994',
      platform: 'Super Nintendo',
      innovation: 'A timer bar per character, so a turn-based fight had to be played in real time after all.',
      why: 'It proved a cartridge could carry a long story, and made the genre a commercial force outside Japan.',
      funFact: 'The random encounter rate was tuned to make grinding feel necessary. Players spent years asking for a switch to turn it off.',
    },
    play: { kind: 'canvas', create: create1994 },
  },
  {
    id: 'y1996',
    year: 1996,
    label: '1996',
    title: 'ACTUAL POLYGONS',
    tagline: ['1996.', 'EVERYTHING IS MADE OF TRIANGLES NOW.', 'TRY NOT TO LOOK AT THE FOG.'],
    controls: 'MOVE: ↑   TURN: ← →',
    touchControls: 'Drag sideways to turn, up to walk.',
    goal: 'Find every crystal in the fog.',
    theme: 'early3d',
    duration: 45,
    fact: 'Early 3D consoles hid their draw distance behind fog, because the alternative was watching the world appear out of nothing a few metres in front of you.',
    deepDive: {
      developer: 'Nintendo, Sony, Sega and everyone else, simultaneously',
      release: '1996 — Super Mario 64, Quake, Tomb Raider, all within months',
      platform: 'Nintendo 64, PlayStation, PC',
      innovation: 'A camera you control and an analogue stick to move in any direction, which required inventing the modern control scheme from scratch.',
      why: 'Every convention of 3D movement — the stick, the camera behind the shoulder, the fog — was argued out in about eighteen months.',
      funFact: 'PlayStation geometry wobbles because the hardware snapped vertices to whole pixels. The jitter was never intended, and is now a deliberate art style.',
    },
    play: { kind: 'canvas', create: create1996 },
  },
  {
    id: 'y1997',
    year: 1997,
    label: '1997',
    title: 'THE LINE THAT GROWS',
    tagline: ['1997.', 'YOUR PHONE HAS A GAME ON IT.', 'IT IS A LINE.', 'IT IS ENOUGH.'],
    controls: 'MOVE: ARROW KEYS',
    touchControls: 'Swipe to turn.',
    goal: 'Eat your pellets without eating yourself.',
    theme: 'lcd',
    duration: 45,
    fact: 'Nokia put Snake on the 6110 in 1997. It was the first game hundreds of millions of people carried everywhere, years before anyone said the word "smartphone".',
    deepDive: {
      developer: 'Taneli Arm\u00e4nto, at Nokia',
      release: '1997',
      platform: 'Nokia 6110 and almost every Nokia after it',
      innovation: 'A game that fit in a few kilobytes on a monochrome display with no graphics chip at all.',
      why: 'It made the phone a games machine by accident, and set the expectation that a phone comes with something to play.',
      funFact: 'The original idea dates to a 1976 arcade game about two players drawing lines. Snake simply removed the second player.',
    },
    play: { kind: 'canvas', create: create1997 },
  },
  {
    id: 'y2000',
    year: 2000,
    label: '2000',
    title: 'CONNECTING',
    tagline: ['2000.', 'OTHER PEOPLE ARE OUT THERE.', 'THEY ARE ABOUT 420 MILLISECONDS AWAY.'],
    controls: 'CLICK THE TARGETS',
    touchControls: 'Tap the targets.',
    goal: 'Land your hits through 420 milliseconds of lag.',
    theme: 'web2',
    duration: 40,
    fact: 'Playing online meant occupying the household telephone line. A 56k modem negotiated its speed out loud, and anyone picking up the handset ended the match.',
    deepDive: {
      developer: 'Everyone, over dial-up',
      release: 'c. 1996–2002',
      platform: 'PC, modem, one telephone line, one family',
      innovation: 'Client-side prediction: the game guesses what the server will say so your own movement feels instant.',
      why: 'Persistent servers and ladders turned games into places you returned to rather than things you finished.',
      funFact: 'Players learned to aim where an opponent would be rather than where they appeared. High-ping players developed a genuinely different playstyle.',
    },
    play: { kind: 'react', Component: Game2000 },
  },
  {
    id: 'y2001',
    year: 2001,
    label: '2001',
    title: 'NEEDS MANAGEMENT',
    tagline: ['2001.', 'A SIMULATION OF HAVING A LIFE.', 'IT IS MOSTLY ADMIN.'],
    controls: 'CLICK WHAT YOU NEED',
    touchControls: 'Tap the furniture.',
    goal: 'Keep every bar above zero until the day ends.',
    theme: 'web2',
    duration: 50,
    fact: 'The Sims became the best-selling PC game of its time by removing the win condition. There is no score, no enemy, and no ending \u2014 just needs, and a house.',
    deepDive: {
      developer: 'Maxis, designed by Will Wright',
      release: '2000',
      platform: 'PC',
      innovation: 'Characters with autonomous needs, so the simulation keeps happening whether or not you are directing it.',
      why: 'It reached an audience the industry had been ignoring, and for years was the most popular PC game on earth.',
      funFact: 'It was pitched as an architecture simulator. The people walking around were added so you could see whether the house worked.',
    },
    play: { kind: 'canvas', create: create2001 },
  },
  {
    id: 'y2004',
    year: 2004,
    label: '2004',
    title: 'SAVE THE KINGDOM',
    tagline: ['2004.', 'THE WORLD IS ENORMOUS.', 'SO IS THE TO-DO LIST.'],
    controls: 'CLICK TO HARVEST',
    touchControls: 'Tap the buttons.',
    goal: 'Finish the quest. Or make the correct decision.',
    theme: 'web2',
    duration: 45,
    fact: 'World of Warcraft reached roughly 12 million subscribers. The quest structure that drew people in — collect, return, repeat — was also the thing most of them eventually described as a job.',
    deepDive: {
      developer: 'Blizzard Entertainment',
      release: '2004',
      platform: 'PC and Mac',
      innovation: 'A shared persistent world that an ordinary machine could run, with a quest log that explained where to go next.',
      why: 'It normalised the monthly subscription, the guild as a social group, and the idea that a game could be where you spend your evenings for years.',
      funFact: 'The early collection quests often had drop rates below 20 percent, meaning "collect 10" quietly meant "kill 50". The maths was deliberate.',
    },
    play: { kind: 'react', Component: Game2004 },
  },
  {
    id: 'y2009',
    year: 2009,
    label: '2009',
    title: 'TOWER DEMOLITION',
    tagline: ['2009.', 'THE WHOLE INDUSTRY FITS IN A POCKET.', 'IT WOULD LIKE YOUR ATTENTION.'],
    controls: 'DRAG BACK FROM THE SLING AND RELEASE',
    touchControls: 'Pull back from the ball and let go.',
    goal: 'Knock down all three targets before the shots run out.',
    theme: 'flat',
    duration: 45,
    fact: 'Angry Birds cost about a hundred thousand euros to make, sold for less than a coffee, and was downloaded a billion times. It is the moment the phone became the biggest games platform there is.',
    deepDive: {
      developer: 'Rovio, a Finnish studio on its fifty-second game',
      release: '2009',
      platform: 'iPhone, then everything',
      innovation: 'A physics puzzle you play with one finger, where failing is as entertaining as succeeding.',
      why: 'It proved a cheap game could out-earn a console release, and brought in an audience that had never bought a game before.',
      funFact: 'Rovio had nearly gone under after fifty-one games nobody bought. The birds were designed before anyone knew why they were angry.',
    },
    play: { kind: 'canvas', create: create2009 },
  },
  {
    id: 'y2011',
    year: 2011,
    label: '2011',
    title: 'BLOCK WORLD',
    tagline: ['2011.', 'EVERYTHING IS A CUBE.', 'INCLUDING THE PROBLEM.'],
    controls: 'CLICK TO MINE AND PLACE   MOVE: \u2190 \u2192',
    touchControls: 'Tap a block to mine it, tap the sky to place one.',
    goal: 'Build a wall and survive the night.',
    theme: 'flat',
    duration: 50,
    fact: 'Minecraft sold for years while unfinished, had no goals and no tutorial, and became the best-selling game ever made. Its first version was written in about a week.',
    deepDive: {
      developer: 'Markus Persson, then Mojang',
      release: 'Full release 2011, playable from 2009',
      platform: 'Everything, eventually',
      innovation: 'A world made of editable blocks, generated endlessly, where building and destroying use the same verb.',
      why: 'It made selling an unfinished game normal, and made a generation of players into level designers.',
      funFact: 'The thing that explodes was a coding error: a pig model with its dimensions swapped. It was kept.',
    },
    play: { kind: 'canvas', create: create2011 },
  },
  {
    id: 'y2013',
    year: 2013,
    label: '2013',
    title: 'ONE BUTTON, TWO PIPES',
    tagline: ['2013.', 'THE GAME IS FREE.', 'THE GAPS ARE NOT.'],
    controls: 'FLAP: SPACE',
    touchControls: 'Tap to flap.',
    goal: 'Pass the pipes. Buying things is optional.',
    theme: 'flat',
    duration: 45,
    fact: 'Flappy Bird was made in a few days, earned a reported fifty thousand dollars a day from adverts, and was then deleted by its own author, who said it had become too addictive.',
    deepDive: {
      developer: 'Dong Nguyen, alone, in Hanoi',
      release: '2013',
      platform: 'Phones',
      innovation: 'Nothing. That is the point \u2014 one button, one rule, and a difficulty curve that is simply a flat line at "hard".',
      why: 'It showed that distribution, not budget, decides what a hit looks like, and became the template for the punishing free game.',
      funFact: 'After it was pulled, phones with it still installed were listed on auction sites for thousands.',
    },
    play: { kind: 'canvas', create: create2013 },
  },
  {
    id: 'y2016',
    year: 2016,
    label: '2016',
    title: 'CATCH IT',
    tagline: ['2016.', 'THE CREATURES ARE OUTSIDE NOW.', 'SO ARE YOU. UNUSUAL.'],
    controls: 'DRAG FROM THE BALL AND RELEASE',
    touchControls: 'Drag back from the ball and let go.',
    goal: 'Catch them all. The servers permitting.',
    theme: 'flat',
    duration: 40,
    fact: 'Pok\u00e9mon GO put a twenty-year-old collecting game on top of a map of the real world, and within a week had people walking into parks, each other, and occasionally the sea.',
    deepDive: {
      developer: 'Niantic with The Pok\u00e9mon Company',
      release: '2016',
      platform: 'Phones',
      innovation: 'Location as the game board: the map is real, and so is the walking.',
      why: 'It was the first mass-market augmented reality hit, and the clearest demonstration that a phone game could change where people physically go.',
      funFact: 'Its servers fell over almost immediately. The launch was paused country by country while the company bought more of the internet.',
    },
    play: { kind: 'canvas', create: create2016 },
  },
  {
    id: 'y2017',
    year: 2017,
    label: '2017',
    title: 'NINETY-NINE OTHERS',
    tagline: ['2017.', 'ONE HUNDRED PLAYERS.', 'NINETY-NINE PROBLEMS, RESOLVING THEMSELVES.'],
    controls: 'MOVE: ARROW KEYS',
    touchControls: 'Hold anywhere and steer.',
    goal: 'Be the last one standing. Try not to help.',
    theme: 'modern',
    duration: 35,
    fact: 'Battle royale came out of mod culture — community-made rulesets for existing games — before anyone built a standalone one. Within a year it was the shape of the biggest game in the world.',
    deepDive: {
      developer: 'Brendan Greene, then PUBG Corporation and Epic Games',
      release: '2017',
      platform: 'PC and console, then phones',
      innovation: 'A shrinking play area that forces an ending, which solved the problem of matches that never finish.',
      why: 'It made a game a place to meet friends, and turned the free seasonal update into the default business model for big games.',
      funFact: 'The shrinking circle exists purely as a pacing device. Without it, a hundred cautious players would simply hide until everyone logged off.',
    },
    play: { kind: 'canvas', create: create2017 },
  },
  {
    id: 'y2026',
    year: 2026,
    label: '2020s',
    title: 'PLEASE WAIT',
    tagline: ['THE 2020s.', '12,000 PEOPLE WORKED ON THIS GAME.', "YOU'RE PRESSING ONE BUTTON."],
    controls: 'PRESS SPACE. EVENTUALLY.',
    touchControls: 'Tap. Then tap again.',
    goal: 'Get to the gameplay. It is one button.',
    theme: 'modern',
    duration: 45,
    fact: 'A modern blockbuster credits thousands of people across several countries, ships a day-one patch larger than every game on this timeline combined, and still has to compile its shaders on your machine before you can move.',
    deepDive: {
      developer: 'Several studios, several continents, several years',
      release: 'The 2020s',
      platform: 'Consoles, PC, streaming, phones, whatever is next',
      innovation: 'Photoreal rendering, enormous worlds, and patching as a permanent condition rather than an emergency.',
      why: 'Budgets now rival film, which makes risk expensive and sequels safe. The interesting work increasingly happens in smaller teams.',
      funFact: 'Shader compilation happens on your hardware because there are too many possible GPU combinations to pre-build. That progress bar is your own computer doing the studio’s last build step.',
    },
    play: { kind: 'react', Component: Game2026 },
  },
];

export const eraById = (id: string) => ERAS.find((e) => e.id === id);
export const nextEra = (id: string) => {
  const i = ERAS.findIndex((e) => e.id === id);
  return i >= 0 && i < ERAS.length - 1 ? ERAS[i + 1] : null;
};
